version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.Dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - backend
    ports:
      - ${DB_PORT}:${DB_PORT}

networks:
  backend:
    driver: bridge